import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../src/App'
import { applyPersonalDraft, personalTexts } from '../src/data/personalContent'
import { caseDefinitions, safeExternalUrl } from '../src/data/caseCatalog'
import { siteSettings } from '../src/lib/mockData'
import { loadAdminData, saveSettings } from '../src/lib/portfolioApi'

vi.mock('../src/lib/motion-runtime', () => ({ MotionRuntime: () => null }))
beforeEach(() => {
  localStorage.clear(); sessionStorage.clear()
  localStorage.setItem('studio-session', '1'); sessionStorage.setItem('studio-preloader-seen', '1')
  window.matchMedia = vi.fn().mockReturnValue({ matches: true, addEventListener: vi.fn(), removeEventListener: vi.fn() })
  window.scrollTo = vi.fn()
  globalThis.IntersectionObserver = class { observe() {} disconnect() {} unobserve() {} } as unknown as typeof IntersectionObserver
})
afterEach(() => { cleanup(); vi.restoreAllMocks() })

describe('personal case editing and content boundaries', () => {
  it('adds a hidden custom case with content/media groups, renames it without breaking its path, and publishes after saving', async () => {
    await saveSettings(applyPersonalDraft(siteSettings))
    const view = render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await screen.findByLabelText('第 1 屏 · 首屏大标题（中文）')
    fireEvent.click(screen.getByRole('button', { name: '案例内容' }))
    fireEvent.change(screen.getByLabelText('新案例名称'), { target: { value: '城市实验' } })
    fireEvent.click(screen.getByRole('button', { name: '添加案例' }))
    expect(screen.getByRole('tab', { name: '城市实验' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByRole('checkbox', { name: '显示此案例' })).not.toBeChecked()
    fireEvent.change(screen.getByLabelText('城市实验 / 内容 · 后台标签名称（中文）'), { target: { value: '城市档案' } })
    expect(screen.getByRole('tab', { name: '城市档案' })).toHaveAttribute('aria-selected', 'true')
    fireEvent.change(screen.getByLabelText('城市档案 / 内容 · 项目标题（中文）'), { target: { value: '我的城市故事' } })
    fireEvent.click(screen.getByRole('checkbox', { name: '显示此案例' }))
    fireEvent.click(screen.getByRole('tab', { name: '媒体' }))
    expect(screen.getByLabelText('城市档案 / 媒体 · 视频 1 标题（中文）')).toBeInTheDocument()
    expect(screen.getByLabelText('编辑图片位置').querySelectorAll('option')).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    const saved = (await loadAdminData()).settings
    const id = saved.content!.customCases![0].id
    expect(saved.content!.images[`case.${id}.cover`]).toBeDefined()
    view.unmount()
    const publicView = render(<MemoryRouter initialEntries={['/work']}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '我的城市故事' })
    expect(screen.getByRole('heading', { name: '我的城市故事' }).closest('a')).toHaveAttribute('href', `/cases/${id}`)
    publicView.unmount()
    render(<MemoryRouter initialEntries={[`/cases/${id}`]}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '我的城市故事' })
    expect(document.querySelectorAll('video')).toHaveLength(2)
  })

  it('locates capability and contact fields from preview clicks and saves editable footer social links', async () => {
    render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await screen.findByLabelText('第 1 屏 · 首屏大标题（中文）')
    fireEvent.click(screen.getByRole('tab', { name: '能力区' }))
    const preview = () => within(screen.getByRole('complementary', { name: '区块预览' }))
    fireEvent.click(preview().getByRole('button', { name: '影像与动态' }))
    expect(screen.getByRole('tab', { name: '能力二' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByLabelText('能力二 · 能力标题（中文）')).toHaveFocus()
    fireEvent.click(preview().getByAltText('山间湖泊'))
    expect(screen.getByLabelText('编辑图片位置')).toHaveValue('mountainLake')
    fireEvent.click(screen.getByRole('button', { name: '联系内容' }))
    fireEvent.click(preview().getByRole('button', { name: '深圳' }))
    expect(screen.getByRole('tab', { name: '地点与时间' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getByLabelText('地点与时间 · 城市 / 地址（中文）')).toHaveFocus()
    fireEvent.click(screen.getByRole('button', { name: '页脚内容' }))
    fireEvent.click(preview().getByRole('img', { name: 'Starry Ink' }))
    expect(screen.getByLabelText('页脚文字 · 页尾互动大字（中文）')).toHaveFocus()
    fireEvent.change(screen.getByLabelText('页脚文字 · 页尾互动大字（中文）'), { target: { value: 'Starry Ink Studio' } })
    expect(preview().getByRole('img', { name: 'Starry Ink Studio' })).toBeInTheDocument()
    fireEvent.click(preview().getByRole('link', { name: 'Instagram ↗' }))
    expect(screen.getByRole('tab', { name: '社交平台' })).toHaveAttribute('aria-selected', 'true')
    fireEvent.click(screen.getByRole('button', { name: '添加社交平台' }))
    const number = siteSettings.socialLinks.length + 1
    fireEvent.change(screen.getByLabelText(`社交名称 ${number}`), { target: { value: 'B站 · Starry' } })
    fireEvent.change(screen.getByLabelText(`社交地址 ${number}`), { target: { value: 'https://space.bilibili.com/789067' } })
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    expect((await loadAdminData()).settings.socialLinks.at(-1)).toEqual({ label: 'B站 · Starry', href: 'https://space.bilibili.com/789067' })
    expect((await loadAdminData()).settings.content?.texts['footer.wordmark'].zh).toBe('Starry Ink Studio')
    expect(preview().getByRole('link', { name: 'B站 · Starry ↗' })).toHaveAttribute('target', '_blank')
  })
  it('shows cases inside the homepage hero and enters a case only through an explicit link', async () => {
    await saveSettings(applyPersonalDraft(siteSettings))
    render(<MemoryRouter><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '让想法被看见' })
    const hero = within(screen.getByRole('region', { name: '首页轮播' }))
    expect(screen.queryByRole('region', { name: '项目案例' })).not.toBeInTheDocument()
    fireEvent.click(hero.getByRole('button', { name: '切换轮播：个人 IP 与内容运营' }))
    expect(hero.getByRole('heading', { name: '个人 IP 与内容运营' })).toBeInTheDocument()
    fireEvent.click(hero.getByRole('link', { name: '查看案例' }))
    await screen.findByRole('heading', { name: '项目概览' })
    expect(screen.getByRole('heading', { name: '个人 IP 与内容运营' })).toBeInTheDocument()
  })

  it('applies approved figures while retaining the existing portrait, theme, contacts, and videos', () => {
    const initial = { ...siteSettings, accent: '#728793', theme: { footerColor: '#123456' }, content: { texts: {}, images: { about: { src: 'https://example.com/portrait.jpg', assetId: 'keep-me', alt: 'current portrait' } }, videos: { existing: { src: 'https://example.com/video.mp4', alt: 'keep' } } } }
    const draft = applyPersonalDraft(initial)
    expect(draft.content?.images).toEqual(initial.content.images)
    expect(draft.content?.videos).toEqual(initial.content.videos)
    expect(draft.theme).toEqual(initial.theme)
    expect(draft.contactEmail).toBe(initial.contactEmail)
    expect(draft.content?.texts['home.stat.0.value'].zh).toBe('7 万')
    expect(draft.content?.texts['home.stat.0.label'].zh).toContain('历史最高 8.3 万')
    expect(draft.content?.texts['home.stat.2.label'].zh).toContain('项目众筹')
    expect(JSON.stringify(personalTexts)).not.toMatch(/入住率|毕业|学历|黄翠莹|⻩翠莹|1998|98%/)
  })

  it('round trips editable replacement pages, external videos and route details without erasing existing videos', async () => {
    const draft = applyPersonalDraft(siteSettings)
    draft.content!.videos = { 'case.plugin.video.0': { src: 'https://example.com/clip.mp4', alt: 'Project video' } }
    await saveSettings(draft)
    const view = render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await screen.findByLabelText('第 1 屏 · 首屏大标题（中文）')
    fireEvent.click(screen.getByRole('button', { name: '案例内容' }))
    fireEvent.click(screen.getByRole('tab', { name: 'AI 插件 / 可替换项目' }))
    fireEvent.change(screen.getByLabelText('AI 插件 / 可替换项目 / 内容 · 项目标题（中文）'), { target: { value: '我的新工具项目' } })
    expect(within(screen.getByRole('complementary', { name: '区块预览' })).getByRole('heading', { name: '我的新工具项目' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('tab', { name: '媒体' }))
    fireEvent.change(screen.getByLabelText('AI 插件 / 可替换项目 / 媒体 · 视频 1 外部页面链接（如 B 站）（中文）'), { target: { value: 'https://www.bilibili.com/video/BVtest' } })
    fireEvent.click(screen.getByRole('tab', { name: '旅居 / 影像与路线' }))
    fireEvent.click(screen.getByRole('tab', { name: '路线' }))
    fireEvent.change(screen.getByLabelText('旅居 / 路线 · 站点 1 名称（中文）'), { target: { value: '深圳海岸' } })
    fireEvent.change(screen.getByLabelText('旅居 / 路线 · 站点 1 路线 / 地图链接（HTTPS）（中文）'), { target: { value: 'https://example.com/route' } })
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    expect((await loadAdminData()).settings.content?.videos?.['case.plugin.video.0'].src).toBe('https://example.com/clip.mp4')
    view.unmount()
    const detail = render(<MemoryRouter initialEntries={['/cases/plugin']}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '我的新工具项目' })
    expect(screen.getByRole('link', { name: /打开原视频页面/ })).toHaveAttribute('href', 'https://www.bilibili.com/video/BVtest')
    fireEvent.click(screen.getAllByRole('button', { name: '切换语言' })[0])
    await screen.findByRole('heading', { name: 'From visual intent to tools' })
    detail.unmount(); localStorage.setItem('studio-language', 'zh')
    render(<MemoryRouter initialEntries={['/cases/travel']}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '深圳海岸' })
    expect(screen.getByRole('link', { name: '查看路线 ↗' })).toHaveAttribute('href', 'https://example.com/route')
  })

  it('hides a disabled case from the collection and direct route', async () => {
    const draft = applyPersonalDraft(siteSettings)
    await saveSettings(draft)
    const admin = render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await screen.findByLabelText('第 1 屏 · 首屏大标题（中文）')
    fireEvent.click(screen.getByRole('button', { name: '案例内容' }))
    fireEvent.click(screen.getByRole('tab', { name: 'AI 插件 / 可替换项目' }))
    fireEvent.click(screen.getByRole('checkbox', { name: '显示此案例' }))
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    expect((await loadAdminData()).settings.content?.texts['case.plugin.visible']).toEqual({ zh: '0', en: '0' })
    admin.unmount()
    const view = render(<MemoryRouter initialEntries={['/work']}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '策划与项目实践' })
    expect(screen.queryByRole('link', { name: /把审美语言变成工具/ })).not.toBeInTheDocument()
    view.unmount()
    render(<MemoryRouter initialEntries={['/cases/plugin']}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '案例暂未公开' })
  })

  it('rejects executable and credential-bearing links and has six stable replaceable case slots', () => {
    for (const value of ['javascript:alert(1)', '//evil.com', 'data:text/html,test', 'https://user:password@example.com']) expect(safeExternalUrl(value)).toBe('')
    expect(safeExternalUrl('https://www.bilibili.com/video/test')).toContain('bilibili.com')
    expect(new Set(caseDefinitions.map(item => item.id)).size).toBe(6)
  })
})
