import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../src/App'
import { imageVariants, contentSections, contentText } from '../src/lib/siteContent'
import { loadAdminData, loadPublicData, projectPayload, saveProject } from '../src/lib/portfolioApi'
import { projects, siteSettings } from '../src/lib/mockData'

vi.mock('../src/lib/motion-runtime', () => ({ MotionRuntime: () => null }))

beforeEach(() => {
  localStorage.clear(); sessionStorage.clear()
  localStorage.setItem('studio-session', '1')
  sessionStorage.setItem('studio-preloader-seen', '1')
  window.matchMedia = vi.fn().mockReturnValue({ matches: true, addEventListener: vi.fn(), removeEventListener: vi.fn() })
  window.scrollTo = vi.fn()
  globalThis.IntersectionObserver = class { observe() {} disconnect() {} unobserve() {} } as unknown as typeof IntersectionObserver
})
afterEach(() => { cleanup(); vi.restoreAllMocks() })

describe('admin to public content round trip', () => {
  it('saves brand, hero, home manifesto and image and renders the same values publicly after refresh', async () => {
    localStorage.setItem('studio-demo-settings', JSON.stringify({ ...siteSettings, content: { texts: { 'home.heroTitle': { en: 'Old English override', zh: '旧中文覆盖值' } }, images: {} } }))
    const view = render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await waitFor(() => expect(screen.getByLabelText('站点名称')).toHaveValue(siteSettings.siteName))
    fireEvent.change(screen.getByLabelText('站点名称'), { target: { value: '星光影像' } })
    fireEvent.change(screen.getByLabelText('首屏标题（中英文共用）'), { target: { value: '我的真实首页' } })
    fireEvent.change(screen.getByLabelText('图片地址（使用私有媒体时请选择下方媒体库）'), { target: { value: 'https://images.example.com/custom.webp' } })
    fireEvent.change(screen.getByLabelText('图片描述 / Alt'), { target: { value: '我的海岸封面' } })
    fireEvent.change(screen.getByLabelText('宣言与统计 · 宣言（中文）'), { target: { value: '这是后台写入的宣言。' } })
    fireEvent.change(screen.getByLabelText('主色'), { target: { value: '#7caed5' } })
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    view.unmount()
    render(<MemoryRouter initialEntries={['/']}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '我的真实首页' })
    expect(screen.getByRole('link', { name: '星光影像' })).toBeInTheDocument()
    expect(screen.getByText('这是后台写入的宣言。')).toBeInTheDocument()
    expect(screen.getByAltText('我的海岸封面')).toHaveAttribute('src', 'https://images.example.com/custom.webp')
    expect(screen.getByAltText('我的海岸封面')).not.toHaveAttribute('srcset')
    expect(document.documentElement.style.getPropertyValue('--olive-rgb')).toBe('124 174 213')
    expect(document.title).toBe('星光影像 — 我的真实首页')
  })

  it('saves independent Chinese and English homepage copy', async () => {
    const saved = { ...siteSettings, content: { texts: { 'home.heroTitle': { zh: '中文作品集', en: 'English portfolio' } }, images: {} } }
    localStorage.setItem('studio-demo-settings', JSON.stringify(saved))
    render(<MemoryRouter><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '中文作品集' })
    fireEvent.click(screen.getAllByRole('button', { name: '切换语言' })[0])
    await screen.findByRole('heading', { name: 'English portfolio' })
  })

  it('keeps published work public when saving changes, and filters it after taking offline', async () => {
    const project = { ...projects[1], sortOrder: -2, title: '已发布项目修改', cover: projects[1].assets[0].src, coverAlt: projects[1].assets[0].alt }
    await saveProject(project)
    expect((await loadPublicData()).projects[0].title).toBe('已发布项目修改')
    expect((await loadAdminData()).projects.find(item => item.id === project.id)?.status).toBe('published')
    await saveProject(project, 'archived')
    expect((await loadPublicData()).projects.some(item => item.id === project.id)).toBe(false)
    expect((await loadAdminData()).projects.some(item => item.id === project.id)).toBe(true)
  })

  it('uses asset IDs for cover selection even after signed URLs change, and preserves media order', () => {
    const project = { ...projects[1], coverAssetId: projects[1].assets[1].id, cover: 'https://expired.example/old-url', coverAlt: '新的封面 Alt', sortOrder: 7, assets: [...projects[1].assets].reverse() }
    const payload = projectPayload(project)
    expect(payload.cover_asset_id).toBe(project.coverAssetId)
    expect(payload.assets[0]).toMatchObject({ id: project.coverAssetId, position: 0, alt: '新的封面 Alt' })
    expect(payload.status).toBe('published')
    expect(payload.sort_order).toBe(7)
  })

  it('the actual editor saves cover, location, order and title while preserving publication', async () => {
    const project = { ...projects[1], cover: projects[1].assets[0].src, coverAlt: projects[1].assets[0].alt, coverAssetId: projects[1].assets[0].id }
    localStorage.setItem('studio-demo-projects', JSON.stringify([project]))
    render(<MemoryRouter initialEntries={[`/admin/projects/${project.id}`]}><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: project.title })
    fireEvent.change(screen.getByLabelText('标题'), { target: { value: '后台真实操作验证' } })
    fireEvent.change(screen.getByLabelText('拍摄地点'), { target: { value: '上海' } })
    fireEvent.change(screen.getByLabelText('展示顺序（数字越小越靠前）'), { target: { value: '-4' } })
    fireEvent.change(screen.getByLabelText('封面图片'), { target: { value: project.assets[1].id } })
    fireEvent.click(screen.getByRole('button', { name: '下移媒体 1' }))
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('项目已发布。')
    const saved = (await loadPublicData()).projects[0]
    expect(saved).toMatchObject({ title: '后台真实操作验证', location: '上海', status: 'published', sortOrder: -4, coverAssetId: project.assets[1].id })
    expect(saved.assets[0].id).toBe(project.assets[1].id)
    expect(saved.cover).toBe(project.assets[1].src)
  })

  it('uploads a demo image from settings, then persists it through a public reload', async () => {
    const view = render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await screen.findByLabelText('站点名称')
    const file = new File(['image-content'], 'demo-photo.png', { type: 'image/png' })
    fireEvent.change(screen.getByLabelText('上传并替换图片'), { target: { files: [file] } })
    await screen.findByText('图片已上传并选中；保存修改后主站生效。')
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    view.unmount()
    render(<MemoryRouter><App /></MemoryRouter>)
    await waitFor(() => expect(screen.getByAltText('demo-photo')).toHaveAttribute('src', expect.stringContaining('data:image/png;base64,')))
    expect(screen.getByAltText('demo-photo')).not.toHaveAttribute('srcset')
  })

  it('never fabricates thumbnails for uploaded, external or unknown bundled files', () => {
    expect(imageVariants('/images/hero.webp').srcSet).toContain('hero-900.webp')
    expect(imageVariants('/images/custom.webp')).toEqual({})
    expect(imageVariants('https://example.com/photo.webp')).toEqual({})
    expect(imageVariants('https://project.supabase.co/storage/v1/object/sign/media/a.webp?token=expired')).toEqual({})
  })

  it('edits all screenshot sections and images, survives page switching, save and reload, and keeps languages independent', async () => {
    localStorage.setItem('studio-demo-settings', JSON.stringify({ ...siteSettings, shortBio: '旧版自定义简介' }))
    const view = render(<MemoryRouter initialEntries={['/admin/settings']}><App /></MemoryRouter>)
    await screen.findByLabelText('首屏 · 首屏大标题（中文）')
    const edit = (label: string, value: string) => fireEvent.change(screen.getByLabelText(label), { target: { value } })
    edit('首屏 · 首屏大标题（中文）', '我的中文首屏')
    edit('首屏 · 首屏大标题（English）', 'My English hero')
    edit('首屏 · 左上场记（中文）', '场景 / 我自己的故事')
    edit('能力 1 / 摄影 · 能力标题（中文）', '肖像与城市')
    edit('能力 1 / 摄影 · 能力说明（中文）', '后台修改的能力说明')
    fireEvent.click(screen.getByRole('button', { name: '编辑 首页 / 摄影配图 2' }))
    edit('图片地址（使用私有媒体时请选择下方媒体库）', 'https://example.com/capability.jpg')
    edit('图片描述 / Alt', '自己的能力配图')
    fireEvent.click(screen.getByRole('button', { name: '关于内容' }))
    expect(screen.getByLabelText('人物介绍 · 人物简介（中文）')).toHaveValue('旧版自定义简介')
    edit('人物介绍 · 人物简介（中文）', '从后台编辑的中文个人介绍')
    edit('人物介绍 · 人物简介（English）', 'My edited biography')
    edit('人物介绍 · 介绍副标题（中文）', '以我的视角看世界')
    edit('时间线与引言 · 经历 1 年份（中文）', '2019')
    edit('时间线与引言 · 经历 1 标题（中文）', '第一次出发')
    edit('图片地址（使用私有媒体时请选择下方媒体库）', 'https://example.com/my-portrait.jpg')
    edit('图片描述 / Alt', '我的肖像')
    fireEvent.click(screen.getByRole('button', { name: '服务内容' }))
    edit('服务 1 / 品牌故事 · 服务标题（中文）', '品牌影像定制')
    edit('服务 1 / 品牌故事 · 服务标题（English）', 'Custom brand films')
    edit('服务 1 / 品牌故事 · 服务说明（中文）', '后台设置的服务说明')
    edit('服务 1 / 品牌故事 · 交付清单（每行一项）（中文）', '创意提案\n成片交付\n')
    edit('合作流程 · 步骤 1 标题（中文）', '需求沟通')
    edit('合作流程 · 步骤 1 说明（中文）', '先了解真实需求')
    fireEvent.click(screen.getByRole('button', { name: '编辑 服务 / 配图' }))
    edit('图片地址（使用私有媒体时请选择下方媒体库）', 'https://example.com/my-service.jpg')
    edit('图片描述 / Alt', '我的服务配图')
    fireEvent.click(screen.getByRole('button', { name: '首页内容' }))
    expect(screen.getByLabelText('首屏 · 首屏大标题（中文）')).toHaveValue('我的中文首屏')
    fireEvent.click(screen.getByRole('button', { name: '全站内容' }))
    edit('导航状态 · 作品导航（中文）', '我的作品')
    fireEvent.click(screen.getByRole('button', { name: '保存修改' }))
    await screen.findByText('设置已保存，打开或刷新主站即可查看。')
    view.unmount()
    let publicView = render(<MemoryRouter><App /></MemoryRouter>)
    await screen.findByRole('heading', { name: '我的中文首屏' })
    expect(screen.getByText(/场景 \/ 我自己的故事/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /肖像与城市/ })).toBeInTheDocument()
    expect(screen.getByText('后台修改的能力说明')).toBeInTheDocument()
    expect(screen.getByAltText('自己的能力配图')).toHaveAttribute('src', 'https://example.com/capability.jpg')
    expect(screen.getAllByRole('link', { name: '我的作品' })[0]).toHaveAttribute('href', '/work')
    fireEvent.click(screen.getAllByRole('button', { name: '切换语言' })[0])
    await screen.findByRole('heading', { name: 'My English hero' })
    expect(document.title).toBe('STUDIO / 01 — My English hero')
    publicView.unmount()
    localStorage.setItem('studio-language', 'zh')
    publicView = render(<MemoryRouter initialEntries={['/about']}><App /></MemoryRouter>)
    await screen.findByText('从后台编辑的中文个人介绍')
    expect(screen.getByText('以我的视角看世界')).toBeInTheDocument()
    expect(screen.getByText('2019')).toBeInTheDocument()
    expect(screen.getByText('第一次出发')).toBeInTheDocument()
    expect(screen.getByAltText('我的肖像')).toHaveAttribute('src', 'https://example.com/my-portrait.jpg')
    publicView.unmount()
    render(<MemoryRouter initialEntries={['/services']}><App /></MemoryRouter>)
    await screen.findByRole('button', { name: /品牌影像定制/ })
    expect(screen.getByText('后台设置的服务说明')).toBeInTheDocument()
    expect(screen.getByText('+ 成片交付')).toBeInTheDocument()
    expect(screen.queryByText('+ Concept and treatment')).not.toBeInTheDocument()
    expect(screen.getByRole('heading', { name: '需求沟通' })).toBeInTheDocument()
    expect(screen.getByText('先了解真实需求')).toBeInTheDocument()
    expect(screen.getByAltText('我的服务配图')).toHaveAttribute('src', 'https://example.com/my-service.jpg')
  })

  it('preserves legacy content, but gives an explicitly edited language priority over shared biography', () => {
    const settings = { ...siteSettings, shortBio: '旧简介', content: { images: {}, texts: { 'AboutPage.92bac68a': { en: 'English biography', zh: '新的中文简介' } } } }
    expect(contentText(settings, 'AboutPage.92bac68a', 'zh')).toBe('新的中文简介')
    expect(contentText(settings, 'AboutPage.92bac68a', 'en')).toBe('English biography')
    const keys = contentSections.flatMap(section => section.fields.map(field => field.key))
    expect(new Set(keys).size).toBe(keys.length)
    expect(keys.length).toBeLessThanOrEqual(150)
  })
})
