import { deepColor, morandiPalettes, pairedPalettes, defaultPalettes, originalAccent, originalFooter, modePalette, type ColorMode } from '../lib/theme'
import type { SiteSettings } from '../lib/types'

export function ThemeControls({ settings, onChange, onThemeChange, extracting, message, onExtract }: { settings: SiteSettings; onChange: (accent: string, footerColor: string, followHero: boolean, syncAccent?: boolean) => void; onThemeChange?: (theme: SiteSettings['theme']) => void; extracting: boolean; message: string; onExtract: () => void }) {
  const footer = settings.theme?.footerColor ?? deepColor(settings.accent)
  const followHero = settings.theme?.followHero ?? true
  return <section aria-label="网站配色" className="space-y-4 border-y rule py-5">
    <h3 className="text-lg">网站配色</h3>
    <p className="text-sm text-muted">主色用于按钮、标签、强调文字与边框，后台左栏使用共用主色的深色。下方可分别设置日间与夜间的主色、背景、页脚与极光颜色；照片保留原色，保存后全站生效。</p>
    <div className="flex flex-wrap gap-2" aria-label="莫兰迪配色">{morandiPalettes.map(palette => <button type="button" key={palette.name} aria-pressed={settings.accent === palette.accent} onClick={() => onChange(palette.accent, deepColor(palette.accent), false, true)} className="flex min-h-11 items-center gap-2 rounded border rule px-3 text-sm"><span className="h-5 w-5 rounded-full" style={{ backgroundColor: palette.accent }} />{palette.name}</button>)}</div>
    <div className="flex flex-wrap gap-8"><label>共用主色<input aria-label="主色" type="color" className="mt-2 block h-12 w-20" value={settings.accent} onChange={event => onChange(event.target.value, deepColor(event.target.value), false, true)} /><span className="mono text-xs">{settings.accent}</span></label><label>共用页脚背景色<input aria-label="页脚背景色" type="color" className="mt-2 block h-12 w-20" value={footer} onChange={event => onChange(settings.accent, event.target.value, false)} /><span className="mono text-xs">{footer}</span></label></div>
    <p className="text-xs text-muted">选择莫兰迪预设、修改共用主色或头图取色，会统一日夜主色与页脚；也可在下面单独微调两种模式。</p>
    <label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={followHero} onChange={event => onChange(settings.accent, footer, event.target.checked)} />更换首页头图时，自动更新主色与页脚配色</label>
    <p className="text-xs text-muted">取色在浏览器内完成；选择预设或自定义颜色会关闭自动联动，可随时重新开启。</p>
    <div className="flex flex-wrap gap-3"><button type="button" disabled={extracting} onClick={onExtract} className="min-h-11 border rule px-4 text-sm disabled:opacity-50">{extracting ? '正在读取头图颜色…' : '从当前头图取色'}</button><button type="button" onClick={() => onChange(originalAccent, originalFooter, false, true)} className="min-h-11 border rule px-4 text-sm">重置为原始墨绿</button></div>
    {message && <p role="status" className="text-sm">{message}</p>}
    {onThemeChange && <div className="space-y-5 border-t rule pt-5">
      <div><h4 className="mb-3 text-sm">日夜成套配色</h4><div className="flex flex-wrap gap-3">{pairedPalettes.map(palette => <button type="button" key={palette.name} onClick={() => onThemeChange({ ...settings.theme, followHero: false, light: palette.light, dark: palette.dark })} className="flex min-h-11 items-center gap-3 rounded border rule px-4 text-sm"><span className="flex overflow-hidden rounded-full border rule"><span className="h-5 w-3" style={{ background: palette.light.footer }} /><span className="h-5 w-3" style={{ background: palette.dark.glow }} /></span>{palette.name}</button>)}</div><p className="mt-2 text-xs text-muted">一键设置浅色日间与深色夜间，保留内容。深海极光使用更深的午夜蓝页脚。</p></div>
      <label className="block">新访客默认模式<select aria-label="新访客默认模式" value={settings.theme?.defaultMode ?? 'light'} onChange={event => onThemeChange({ ...settings.theme, defaultMode: event.target.value as ColorMode })} className="ml-3 border rule p-2"><option value="light">日间</option><option value="dark">夜间</option></select></label>
      <p className="text-xs text-muted">访客手动选择后会记住其偏好。右侧预览可单独切换日夜，编辑不影响访客当前选择。</p>
      <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={settings.theme?.nightAtmosphere !== false} onChange={event => onThemeChange({ ...settings.theme, nightAtmosphere: event.target.checked })} />夜间蓝黑晕染与星点</label>
      <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={settings.theme?.ambientMotion !== false} onChange={event => onThemeChange({ ...settings.theme, ambientMotion: event.target.checked })} />首页轻柔动效</label>
      <p className="text-xs text-muted">首页共用连续背景，页脚渐变衔接。轻柔动效控制极光缓慢流动和内容淡入；减少动态效果、触屏和编辑预览使用静态光晕。页尾大字的描边与鼠标光斑跟随对应模式的配色。</p>
      <p className="text-xs text-muted">日间推荐暖白搭配浅雾灰蓝，夜间推荐蓝黑；重置对应模式即可使用推荐配色。星点为静态背景，不覆盖照片，后台表单不受影响。</p>
      {(['light', 'dark'] as const).map(mode => <fieldset key={mode} className="border rule p-4"><legend>{mode === 'light' ? '日间' : '夜间'}配色</legend><div className="grid grid-cols-2 gap-4">{([['accent', '主色'], ['background', '页面背景'], ['surface', '次级背景'], ['section', '作品与宣言统计背景'], ['footer', '页脚背景'], ['glow', '光晕颜色']] as const).map(([key, label]) => <label key={key} className="text-sm">{label}<input type="color" aria-label={`${mode === 'light' ? '日间' : '夜间'}${label}`} value={modePalette(settings, mode)[key]} className="mt-2 h-10 w-20" onChange={event => onThemeChange({ ...settings.theme, followHero: false, ...(mode === 'dark' && key === 'glow' ? { nightGlow: event.target.value } : {}), [mode]: { ...settings.theme?.[mode], [key]: event.target.value } })} /><span className="mono text-xs">{modePalette(settings, mode)[key]}</span></label>)}</div><button type="button" className="mt-4 border rule px-3 py-2 text-sm" onClick={() => onThemeChange({ ...settings.theme, [mode]: { ...defaultPalettes[mode], accent: settings.accent, footer } })}>重置{mode === 'light' ? '日间' : '夜间'}配色</button></fieldset>)}
    </div>}
  </section>
}
